CarBrand.create(id: 1, brand: '奥迪', models: ["奥迪A4L", "奥迪A6L", "奥迪Q5L", "奥迪A3", "奥迪Q3", "奥迪Q2L", "奥迪100", "奥迪200", "奥迪A4", "奥迪Q5", "奥迪Q4", "奥迪A7", "奥迪Q7", "奥迪A5", "奥迪A8L", "奥迪A6", "奥迪Q8", "奥迪A4(进口)", "奥迪TT", "奥迪A3(进口)", "奥迪100(海外)", "奥迪80", "奥迪A2", "奥迪Coupe", "奥迪Cross", "奥迪Q3(进口)", "奥迪Q5(进口)", "Nanuk", "奥迪A1", "奥迪A9", "奥迪quattro", "奥迪R18", "奥迪TT offroad", "奥迪Q4(海外)", "奥迪R8", "奥迪RS 7", "奥迪S4", "奥迪S3", "奥迪RS 5", "奥迪RS 4", "奥迪RS 3", "奥迪S5", "奥迪S7", "奥迪RS 6", "奥迪S6", "奥迪TT RS", "奥迪TTS", "奥迪SQ5", "奥迪RS Q3", "奥迪RS Q8", "奥迪S1", "奥迪S8", "奥迪SQ2", "奥迪SQ7", "奥迪SQ8", "奥迪A6L 插电混动", "奥迪Q2L 纯电动", "奥迪e-tron", "奥迪e-tron(进口)", "奥迪Q7 插电混动", "奥迪A3 插电混动(进口)", "奥迪Urban", "Crosslane Coupe", "AI:TRAIL quattro", "奥迪A6 插电混动", "奥迪A7 插电混动", "奥迪A8L 插电混动", "奥迪Aicon", "奥迪AI:ME", "奥迪allroad", "奥迪Elaine", "e-tron GT", "奥迪PB18", "奥迪Q4 e-tron(海外)", "奥迪Q5 插电混动(进口)", "e-tron Concept", "e-tron Vision Gran Turismo", "h-tron quattro", "Prologue"], abc: 'A')
CarBrand.create(id: 2, brand: '阿尔法·罗密欧', models: ["Giulia", "Stelvio", "ALFA 156", "ALFA 166", "ALFA GT", "ALFA 4C", "Tonale"], abc: 'A')
CarBrand.create(id: 3, brand: '阿斯顿·马丁', models: ["V8 Vantage", "阿斯顿·马丁DBX", "阿斯顿·马丁DB11", "阿斯顿·马丁DBS", "Vanquish", "阿斯顿·马丁DB9", "阿斯顿·马丁One-77", "阿斯顿·马丁DB7", "Lagonda", "Rapide", "V12 Vantage", "Virage", "V12 Zagato", "Valhalla", "阿斯顿·马丁CC100", "阿斯顿·马丁DB10", "阿斯顿·马丁DB5", "阿斯顿·马丁DB6", "阿斯顿·马丁DP-100", "V12 SPEEDSTER", "Cygnet", "拉共达Taraf", "Vulcan", "战神", "Rapide E", "Heritage EV"], abc: 'A')
CarBrand.create(id: 4, brand: '爱驰', models: ["爱驰U5", "RG Nathalie", "爱驰U6 ion", "爱驰U7"], abc: 'A')
CarBrand.create(id: 5, brand: 'ABT', models: ["ABT AS3", "ABT AS4", "ABT AS5", "ABT AS6", "ABT AS8", "ABT Q5", "ABT Q7", "ABT R8", "ABT 途锐", "ABT TT"], abc: 'A')
CarBrand.create(id: 6, brand: 'AC Schnitzer', models: ["AC Schnitzer 1系", "AC Schnitzer 2系", "AC Schnitzer 3系", "AC Schnitzer 5系", "AC Schnitzer X1", "AC Schnitzer X6"], abc: 'A')
CarBrand.create(id: 7, brand: '艾康尼克', models: ["艾康尼克7系"], abc: 'A')
CarBrand.create(id: 8, brand: 'ALPINA', models: ["ALPINA B4", "ALPINA B3", "ALPINA D3", "ALPINA D4", "ALPINA D5", "ALPINA XB7"], abc: 'A')
CarBrand.create(id: 9, brand: 'APEX', models: ["APEX AP-0"], abc: 'A')
CarBrand.create(id: 10, brand: 'ARCFOX', models: ["ARCFOX α-T", "ARCFOX ECF", "ARCFOX GT"], abc: 'A')
CarBrand.create(id: 11, brand: 'Aspark', models: ["Aspark Owl"], abc: 'A')
CarBrand.create(id: 12, brand: '宝骏', models: ["宝骏510", "宝骏530", "宝骏730", "宝骏310", "宝骏360", "宝骏310W", "宝骏330", "宝骏560", "宝骏610", "宝骏630", "乐驰", "宝骏E100", "宝骏E200"], abc: 'B')
CarBrand.create(id: 27, brand: '北汽昌河', models: ["北汽昌河Q7", "北汽昌河M50S", "昌河北斗星X5", "北汽昌河Q35", "北汽昌河A6", "北汽昌河M60", "福瑞达K21", "福瑞达K22", "爱迪尔", "昌河北斗星", "北汽昌河M70", "北汽昌河Q25", "福瑞达", "北汽EV2", "北斗星EC100", "北汽EV5", "北斗星X5E"], abc: 'B')
CarBrand.create(id: 28, brand: '北汽制造', models: ["BJ 212", "勇士", "战旗", "勇士皮卡", "角斗士", "越铃", "锐铃", "北京BW007", "雷驰", "陆霸", "陆铃", "骑士S12", "新城市猎人", "旋风", "战旗2023", "战旗皮卡", "北京豹", "北京大猫"], abc: 'B')
CarBrand.create(id: 29, brand: 'BAC', models: ["Mono"], abc: 'B')
CarBrand.create(id: 30, brand: '宝腾', models: ["宝腾X70"], abc: 'B')
CarBrand.create(id: 31, brand: '北京清行', models: ["清行400"], abc: 'B')
CarBrand.create(id: 13, brand: '宝马', models: ["宝马3系", "宝马5系", "宝马X1", "宝马X3", "宝马1系", "宝马X2", "宝马2系旅行车", "宝马X5", "宝马7系", "宝马2系", "宝马X6", "宝马X7", "宝马X4", "宝马Z4", "宝马5系(进口)", "宝马4系", "宝马3系GT", "宝马8系", "宝马6系GT", "宝马2系多功能旅行车", "Active Tourer", "宝马1系(进口)", "宝马2系旅行车(进口)", "宝马3系(进口)", "宝马5系GT", "宝马6系", "宝马GINA", "宝马X1(进口)", "宝马X2(进口)", "宝马X3(进口)", "Isetta", "宝马Z3", "宝马Z8", "2002 Hommage", "3.0 CSL Hommage", "宝马X7皮卡", "Compact Sedan", "ConnectedDrive", "Garmisch", "Gran Lusso", "Vision Future Luxury", "VISION NEXT 100", "Zagato Coupe", "宝马5系 插电混动", "宝马X1 插电混动", "宝马iX3", "宝马M8", "宝马X3 M", "宝马M2", "宝马X5 M", "宝马M4", "宝马M5", "宝马X6 M", "宝马M3", "宝马X4 M", "宝马1系M", "宝马M1", "宝马M6", "宝马i8", "宝马X5 插电混动", "宝马i3", "宝马7系 插电混动", "EfficientDynamics", "宝马3系 插电混动(进口)", "宝马5系 插电混动(进口)", "宝马2系旅行车 插电混动(进口)", "宝马i4", "iNEXT", "宝马iX3(海外)", "宝马X1 插电混动(进口)", "宝马X2 插电混动(进口)", "宝马X3 插电混动(进口)", "宝马X7 插电混动", "i Hydrogen NEXT", "i Vision Dynamics", "i Vision Future Interaction", "VISION M NEXT"], abc: 'B')
CarBrand.create(id: 14, brand: '奔驰', models: ["奔驰C级", "奔驰GLC", "奔驰E级", "奔驰A级", "奔驰GLB", "奔驰GLA", "奔驰GLK级", "奔驰S级", "奔驰G级", "奔驰GLE", "奔驰CLA级", "奔驰GLS", "奔驰C级(进口)", "奔驰GLC(进口)", "奔驰E级(进口)", "奔驰CLS级", "奔驰B级", "奔驰A级(进口)", "奔驰SL级", "奔驰SLC级", "奔驰CLK级", "奔驰CL级", "奔驰GL级", "奔驰GLK级(进口)", "凌特(进口)", "奔驰M级", "奔驰R级", "奔驰SLA级", "唯雅诺(进口)", "奔驰GLA(进口)", "Marco Polo", "奔驰SLK级", "奔驰SLR级", "威霆(进口)", "奔驰Citan", "奔驰CSC级", "奔驰GLB(海外)", "奔驰V级(海外)", "奔驰X级", "Biome", "Concept A Sedan", "Concept IAA", "Metris", "Silver Arrow", "Sprinter", "乌尼莫克U5000 SUV", "迈巴赫S级", "迈巴赫G级", "迈巴赫GLS", "Vision Mercedes-Maybach 6", "至臻豪华概念车", "威霆", "奔驰V级", "凌特", "唯雅诺", "奔驰G级 AMG", "奔驰GT AMG", "奔驰A级 AMG(进口)", "奔驰GLC AMG", "奔驰S级 AMG", "奔驰C级 AMG", "奔驰GLE AMG", "奔驰E级 AMG", "奔驰CLA级 AMG", "奔驰GLS AMG", "奔驰GLA AMG", "奔驰M级 AMG", "奔驰CLS级 AMG", "奔驰GL级 AMG", "奔驰SL级 AMG", "奔驰SLK级 AMG", "奔驰SLS级 AMG", "奔驰GLB AMG", "奔驰A级 AMG", "奔驰EQC", "奔驰E级 插电混动", "奔驰C级 插电混动", "奔驰GLE 插电混动", "奔驰A级 插电混动(进口)", "奔驰B级 插电混动", "奔驰C级 插电混动(进口)", "奔驰CLA级 插电混动", "奔驰E级 插电混动(进口)", "奔驰EQA", "奔驰EQB", "奔驰EQC(海外)", "奔驰EQE", "奔驰EQS", "奔驰EQV", "奔驰F015", "奔驰F125", "奔驰F800", "奔驰S级 插电混动", "VISION AVTR", "BlueZero", "Ener-G-Force", "EQ Silver Arrow", "G-Code", "Generation EQ", "奔驰GLC 插电混动(进口)", "Sprinter 纯电动", "Vision Mercedes Simplex", "Vision Tokyo", "Vision URBANETIC", "Vision Van", "威霆 纯电动(进口)", "AMG ONE"], abc: 'B')
CarBrand.create(id: 15, brand: '本田', models: ["思域", "本田CR-V", "本田XR-V", "INSPIRE", "享域", "本田UR-V", "艾力绅", "哥瑞", "杰德", "竞瑞", "思铂睿", "雅阁", "皓影", "凌派", "冠道", "飞度", "奥德赛", "缤智", "锋范", "思迪", "歌诗图", "奥德赛(进口)", "本田CR-V(海外)", "本田CR-Z", "INSIGHT", "里程", "时韵", "思域(进口)", "雅阁(进口)", "元素", "本田BR-V", "飞度(进口)", "Freed", "本田HR-V", "N-WGN", "Passport", "Pilot", "Ridgeline", "Shuttle", "CLARITY", "本田e"], abc: 'B')
CarBrand.create(id: 16, brand: '别克', models: ["英朗", "君威", "昂科威", "别克GL8", "君越", "威朗", "凯越", "昂科拉", "昂科旗", "昂科拉GX", "别克GL6", "阅朗", "林荫大道", "荣御", "VELITE 5", "Enspire", "ENVISION S", "微蓝", "VELITE 7", "昂科雷"], abc: 'B')
CarBrand.create(id: 17, brand: '标致', models: ["标致508L", "标致2008", "标致5008", "标致408", "标致4008", "标致308", "标致3008", "标致301", "标致206", "标致207", "标致307", "标致308S", "标致508", "标致e2008", "标致4008 PHEV", "标致508L PHEV", "标致206(进口)", "标致207(进口)", "标致3008(进口)", "标致307(进口)", "标致308(进口)", "标致RCZ", "标致4008(进口)", "标致406", "标致407", "标致607", "标致807", "标致107", "标致108", "标致2008(海外)", "标致208", "标致301(海外)", "标致4007", "标致5008(海外)", "标致5008经典", "标致508(海外)", "标致HR1", "标致iOn", "Landtrek", "Boxer", "EXALT", "Expert", "ONYX", "Partner", "Pick Up", "Rifter", "TRAVELLER", "Urban Crossover", "Vision Gran Turismo", "5 by Peugeot", "标致3008 PHEV(进口)", "标致508 PHEV(海外)", "标致BB1", "标致e2008(海外)", "标致e-208", "标致EX1", "标致HX1", "标致SR1", "标致SXC", "e-Legend", "Fractal", "Instinct", "L500 R HYBRID", "Quartz"], abc: 'B')
CarBrand.create(id: 18, brand: '比亚迪', models: ["宋Pro", "秦", "宋", "秦Pro", "唐", "比亚迪F3", "宋MAX", "元", "比亚迪G6", "比亚迪S7", "比亚迪F0", "比亚迪F6", "比亚迪G3", "比亚迪G5", "比亚迪L3", "比亚迪M6", "比亚迪S6", "比亚迪S8", "福莱尔", "思锐", "速锐", "宋PLUS", "元EV", "唐DM", "比亚迪e2", "唐EV", "宋Pro DM", "秦EV", "宋Pro EV", "宋MAX DM", "比亚迪e1", "秦DM", "秦Pro DM", "秦Pro EV", "比亚迪S2", "比亚迪e3", "宋MAX EV", "汉EV", "汉DM", "比亚迪e5", "比亚迪F3 DM", "比亚迪e6", "宋DM", "宋EV", "元 插电混动", "比亚迪e-SEED GT", "比亚迪T3", "商", "宋PLUS EV"], abc: 'B')
CarBrand.create(id: 19, brand: '保时捷', models: ["Panamera", "Macan", "Cayenne", "保时捷718", "保时捷911", "918 Spyder", "Boxster", "Cayman", "919 Hybrid", "981 Bergspyder", "保时捷356", "保时捷917", "保时捷935", "保时捷968", "Carrera GT", "Taycan", "Panamera 插电混动", "Cayenne 插电混动", "Mission E"], abc: 'B')
CarBrand.create(id: 20, brand: '宝沃', models: ["宝沃BX5", "宝沃BX7", "宝沃BX3", "宝沃BX6", "宝沃BXi7", "宝沃BXi5"], abc: 'B')
CarBrand.create(id: 21, brand: '奔腾', models: ["奔腾T77", "奔腾T99", "奔腾X40", "奔腾T33", "奔腾X80", "奔腾B70", "奔腾B50", "奔腾B30", "奔腾B90", "奔腾X40 EV", "奔腾B30 EV", "奔腾E01"], abc: 'B')
CarBrand.create(id: 22, brand: '比速', models: ["比速T5", "比速T3", "比速M3", "比速T7"], abc: 'B')
CarBrand.create(id: 23, brand: '北京汽车', models: ["BEIJING·X3", "BEIJING·U7", "绅宝X35", "绅宝D50", "绅宝X25", "智行", "绅宝X65", "绅宝D70", "BEIJING·X7", "北京汽车E系列", "绅宝D60", "绅宝CC", "绅宝D20", "绅宝D80", "绅宝X55", "BEIJING·U5", "耀"], abc: 'B')
CarBrand.create(id: 24, brand: '北汽新能源', models: ["北汽新能源EC", "北汽新能源EU5", "LITE", "北汽新能源EC3", "北汽新能源EC5", "北汽新能源EU", "北汽新能源EX3", "北汽新能源EX", "BEIJING·EU7", "北汽新能源EX5", "北汽新能源EH", "北汽新能源EV", "北汽新能源ES"], abc: 'B')
CarBrand.create(id: 25, brand: '北汽幻速', models: ["幻速S3", "幻速H2", "幻速H6", "幻速S7", "幻速S6", "幻速S5", "幻速H5", "幻速H3", "幻速S2"], abc: 'B')
CarBrand.create(id: 26, brand: '北汽威旺', models: ["威旺M20", "威旺M30", "威旺S50", "威旺M50F", "威旺M60", "威旺307", "威旺306", "威旺M35", "威旺205", "威旺EV"], abc: 'B')
CarBrand.create(id: 32, brand: '北汽道达', models: ["道达V8"], abc: 'B')
CarBrand.create(id: 33, brand: '比德文汽车', models: ["比德文E3"], abc: 'B')
CarBrand.create(id: 34, brand: '宾尼法利纳', models: ["Battista", "H2 Speed", "Pura Vision"], abc: 'B')
CarBrand.create(id: 35, brand: '铂驰', models: ["铂驰T6系列", "铂驰Sprinter系列", "铂驰V系列"], abc: 'B')
CarBrand.create(id: 36, brand: '博郡汽车', models: ["博郡iV6", "博郡iV7"], abc: 'B')
CarBrand.create(id: 37, brand: 'Bollinger Motors', models: ["Bollinger B1", "Bollinger B2"], abc: 'B')
CarBrand.create(id: 38, brand: '北京', models: ["北京BJ40", "北京BJ80", "北京BJ90", "北京BJ20", "北京F40"], abc: 'B')
CarBrand.create(id: 39, brand: '拜腾', models: ["拜腾K-Byte", "拜腾M-Byte"], abc: 'B')
CarBrand.create(id: 40, brand: '宾利', models: ["飞驰", "欧陆", "添越", "慕尚", "雅骏", "雅致", "宾利Mulliner Bacalar", "添越PHEV", "宾利EXP 100 GT"], abc: 'B')
CarBrand.create(id: 41, brand: '布加迪', models: ["Galibier", "威航", "Atlantic", "Chiron", "布加迪Vision GT", "Centodieci", "Divo", "La Voiture Noire"], abc: 'B')
CarBrand.create(id: 42, brand: '巴博斯', models: ["巴博斯C级", "巴博斯CLS级", "巴博斯G级", "巴博斯M级", "巴博斯S级", "巴博斯SLK级", "巴博斯A级", "巴博斯B级", "巴博斯CL级", "巴博斯E级", "巴博斯GLA", "巴博斯GLC", "巴博斯GLE", "巴博斯GLS", "巴博斯GT", "巴博斯SL级", "巴博斯SLS级", "巴博斯V级", "巴博斯X级", "巴博斯EQC级"], abc: 'B')
CarBrand.create(id: 43, brand: '长安汽车', models: ["长安CS75 PLUS", "逸动", "长安CS35 PLUS", "长安CS75", "长安CS55 PLUS", "长安CS85 COUPE", "长安CS55", "长安CS35", "长安CS95", "锐程CC", "逸动DT", "长安CS15", "悦翔", "逸动XT", "睿骋CC", "奔奔", "凌轩", "睿骋", "长安UNI-T", "奔奔MINI", "悦翔V3", "长安CX20", "长安CX30", "杰勋", "悦翔V5", "悦翔V7", "志翔", "长安CS15 EV", "长安CS75 PHEV", "奔奔EV", "逸动PHEV", "逸动EV", "逸动ET", "长安CS15 E-Pro", "奔奔E-Star", "长安CS55 E-Rock", "奔奔mini-e", "逸动E-Life"], abc: 'C')
CarBrand.create(id: 44, brand: 'Caterham', models: ["Seven"], abc: 'C')
CarBrand.create(id: 45, brand: '长安凯程', models: ["欧诺S", "神骐F30", "长安星卡", "凯程F70", "神骐T20", "睿行S50", "长安之星9", "长安之星5", "睿行M90", "睿行M80", "睿行M60", "神骐T10", "长安星卡L1", "长安星卡C系列", "睿行S50T", "睿行M70", "长安CM8", "镭蒙", "长安之星", "长安之星2", "长安之星3", "尊行", "长安之星7", "神骐F50", "长安星卡EV", "长安之星9 EV", "欧诺S EV", "睿行EM60", "睿行EM80", "睿行ES30", "神骐T10 EV"], abc: 'C')
CarBrand.create(id: 46, brand: '长安欧尚', models: ["长安欧尚X7", "长安欧尚X70A", "长安欧尚CX70", "长安欧尚科赛", "长安欧尚科尚", "长安欧尚A600", "长安欧尚A800", "长安欧尚科赛5", "欧尚长行", "长安欧尚科赛3", "欧力威", "长安欧尚X5", "欧尚A600 EV", "长安欧尚科尚EV", "欧尚长行EV", "欧尚EV", "长安欧尚X7 EV", "尼欧II", "欧力威EV", "欧尚E01"], abc: 'C')
CarBrand.create(id: 47, brand: '车驰汽车', models: ["车驰Daily", "车驰Sprinter", "车驰T系列", "车驰V-Class"], abc: 'C')
CarBrand.create(id: 48, brand: 'Cupra', models: ["Cupra Ateca", "Cupra e-Racer", "Formentor", "Cupra Leon 插电混动", "Tavascan"], abc: 'C')
CarBrand.create(id: 49, brand: 'Czinger', models: ["Czinger 21C"], abc: 'C')
CarBrand.create(id: 50, brand: '长安跨越', models: ["长安跨越王X5", "新豹T3", "长安新豹MINI", "长安跨越V3", "跨越王X1", "跨越者D5", "新豹3", "长安跨越V5", "跨越王X3", "长安新豹2", "长安跨越V5厢式车", "长安跨越新能源V3 EV", "长安跨越新能源V5 EV"], abc: 'C')
CarBrand.create(id: 51, brand: '长城', models: ["炮", "风骏5", "风骏7", "风骏6", "精灵", "长城M2", "长城C20R", "长城M4", "长城V80", "金迪尔", "酷熊", "凌傲", "赛弗", "赛骏", "赛影", "长城C30", "长城C50", "炫丽", "长城C30 EV", "风骏7 EV", "炮EV"], abc: 'C')
CarBrand.create(id: 52, brand: '成功', models: ["成功BEV6", "成功V2E"], abc: 'C')
CarBrand.create(id: 53, brand: '大众', models: ["迈腾", "宝来", "速腾", "探岳", "高尔夫", "探歌", "一汽-大众CC", "探影", "蔚领", "高尔夫·嘉旅", "捷达", "开迪", "探岳X", "一汽-大众SMV", "朗逸", "桑塔纳", "帕萨特", "途岳", "途观L", "凌渡", "途昂", "Polo", "途观", "途铠", "辉昂", "途昂X", "途安L", "高尔", "朗境", "朗行", "途安", "威然", "途锐", "甲壳虫", "高尔夫(进口)", "Tiguan", "蔚揽", "夏朗", "迈特威", "凯路威", "大众CC", "Amarok", "大众Eos", "辉腾", "迈腾(进口)", "大众up!", "大众XL1", "尚酷", "Arteon", "大众Atlas", "Passat", "T-ROC(海外)", "开迪(海外)", "Nivus", "Polo(海外)", "Taigun", "T-Cross(海外)", "途观L 插电混动", "帕萨特 插电混动", "朗逸纯电", "上汽大众ID.", "途岳纯电", "探岳GTE 插电混动", "迈腾GTE 插电混动", "宝来·纯电", "高尔夫·纯电", "蔚揽 插电混动", "高尔夫 纯电动(进口)", "高尔夫 插电混动(进口)", "大众ID.3", "大众ID.4", "大众I.D.R Pikes Peak", "ID. Space Vizzion", "大众e-up！", "e-Bulli", "ID. BUGGY", "e-Beetle", "Passat 插电混动", "途锐 插电混动"], abc: 'D')
CarBrand.create(id: 54, brand: '大乘汽车', models: ["大乘G60S", "大乘G70S", "大乘G60", "大乘E20", "大乘G60E"], abc: 'D')
CarBrand.create(id: 55, brand: 'Dacia', models: ["Spring"], abc: 'D')
CarBrand.create(id: 56, brand: '大发', models: ["大发Copen", "大发Rocky", "大发Waku Waku", "TAFT", "大发ICO ICO", "大发Tsumu Tsumu", "大发Wai Wai"], abc: 'D')
CarBrand.create(id: 57, brand: '大运汽车', models: ["大运皮卡", "驰虎EM6", "悦虎ES3"], abc: 'D')
CarBrand.create(id: 58, brand: '东风风度', models: ["风度MX6", "风度MX5", "风度MX3"], abc: 'D')
CarBrand.create(id: 59, brand: '东风风光', models: ["风光580", "风光S560", "风光580Pro", "风光330", "风光ix5", "风光ix7", "风光370", "风光360", "风光580 PHEV", "风光E1", "风光E3 电动版", "风光E3 增程版"], abc: 'D')
CarBrand.create(id: 60, brand: '东风风神', models: ["奕炫", "风神AX7", "风神AX4", "风神AX5", "风神A60", "风神AX3", "奕炫GS", "风神A30", "东风A9", "风神S30", "风神H30", "风神L60", "风神E70", "奕炫EV", "风神E30", "风神AX7 FCV", "风神AX7 PHEV", "风神EX1"], abc: 'D')
CarBrand.create(id: 61, brand: '东风风行', models: ["菱智", "风行T5", "风行SX6", "风行T5L", "景逸X5", "景逸S50", "风行CM7", "风行S500", "风行M7", "风行M6", "风行F600", "景逸", "景逸SUV", "景逸X3", "景逸X6", "景逸XV", "菱智M5 EV", "风行S50 EV", "风行T1 EV"], abc: 'D')
CarBrand.create(id: 62, brand: '东风富康', models: ["富康ES500", "富康e爱丽舍"], abc: 'D')
CarBrand.create(id: 63, brand: '东风小康', models: ["东风小康K01", "小康K07S", "东风小康C32", "东风小康K02", "东风小康C31", "东风小康D52", "小康K05S", "东风小康C37", "东风小康D51", "东风小康C36", "东风小康C35", "东风小康C51", "东风小康C52", "东风小康K07", "东风小康K07Ⅱ", "东风小康K17", "东风小康V21", "东风小康V22", "东风小康V27", "东风小康V29", "东风小康V07S", "东风小康V26", "东风小康D55", "东风小康EC36"], abc: 'D')
CarBrand.create(id: 64, brand: '东风', models: ["锐骐6", "帅客", "锐骐", "奥丁", "俊风", "锐骐厢式车", "御轩", "御风S16", "御风A100", "御风P16", "御风领航版", "御风领御版", "御风领运版", "御风领尊版", "东风EM10", "东风EV350", "俊风E11K", "俊风E17", "东风EM13", "俊风ER30", "锐骐EV", "帅客EV", "锐骐6 EV", "物流王", "御风EA100", "虎视", "猛士", "东风皮卡"], abc: 'D')
CarBrand.create(id: 65, brand: '东风·瑞泰特', models: ["东风·瑞泰特EM10", "东风·瑞泰特EM30", "东风·瑞泰特EM13"], abc: 'D')
CarBrand.create(id: 66, brand: '东南', models: ["东南DX3", "A5翼舞", "东南DX7", "东南DX5", "V5菱致", "得利卡", "希旺", "V6菱仕", "富利卡", "菱利", "菱帅", "V3菱悦", "东南DX9", "东南DX3 EV"], abc: 'D')
CarBrand.create(id: 67, brand: '道奇', models: ["酷威", "锋哲", "道奇Ram", "凯领(进口)", "酷搏", "Charger", "Durango", "道奇M80", "Dart", "挑战者", "翼龙", "凯领", "Circuit EV", "Charger SRT", "Durango SRT", "蝰蛇", "挑战者 SRT"], abc: 'D')
CarBrand.create(id: 68, brand: 'DS', models: ["DS 7", "DS 6", "DS 5LS", "DS 5", "DS 4S", "DS 9", "DS 3", "DS 5(进口)", "DS 4", "DS 9(海外)", "DS Aero Sport Lounge", "DS 3 纯电动", "DS 9 插电混动(海外)", "DS 9 插电混动"], abc: 'D')
CarBrand.create(id: 69, brand: '电咖', models: ["电咖EV10"], abc: 'D')
CarBrand.create(id: 70, brand: '丰田', models: ["卡罗拉", "RAV4荣放", "亚洲龙", "普拉多", "威驰", "奕泽", "皇冠", "威驰FS", "柯斯达", "花冠", "兰德酷路泽", "陆地巡洋舰", "普锐斯", "锐志", "特锐", "汉兰达", "凯美瑞", "雷凌", "威兰达", "YARiS L 致炫", "丰田C-HR", "YARiS L 致享", "逸致", "雅力士", "埃尔法", "丰田86", "威尔法", "柯斯达(进口)", "HIACE", "汉兰达(进口)", "红杉", "凯美瑞(进口)", "兰德酷路泽(进口)", "坦途", "普拉多(进口)", "普瑞维亚", "Wish", "FJ酷路泽", "Fortuner", "海拉克斯", "威飒", "杰路驰", "4Runner", "Aygo", "丰田C-HR(海外)", "Granvia", "GR Super Sport", "Harrier", "RAIZE", "Sienna", "Supra", "YARiS(海外)", "亚洲龙(海外)", "皇冠(进口)", "PROACE", "Tacoma", "Tj Cruiser", "YARiS Cross", "卡罗拉 双擎E+", "奕泽 E进擎", "雷凌 双擎E+", "丰田C-HR EV", "丰田APM", "丰田e-4me", "丰田e-Care", "丰田e-Palette", "丰田e-RACER", "丰田e-Trans", "丰田LQ", "Mirai", "丰田RAV4 插电混动(进口)", "Ultra-compact BEV"], abc: 'F')
CarBrand.create(id: 71, brand: '福特', models: ["福睿斯", "福克斯", "蒙迪欧", "锐界", "锐际", "金牛座", "翼虎", "翼搏", "福克斯Active", "麦柯斯", "嘉年华", "探险者", "领界", "撼路者", "全顺", "途睿欧", "新世代全顺", "经典全顺", "Mustang", "探险者(进口)", "福特F-150", "Ranger", "福克斯(进口)", "锐界(进口)", "福特E系列", "FLEX", "外交官", "翼虎(进口)", "嘉年华(进口)", "福特征服者", "Airstream", "B-MAX", "C-MAX", "Crown Victoria", "Falcon", "Figo", "福睿斯(海外)", "福特4-Trac", "福特Atlas", "Bronco", "福特F-250", "福特F-350", "福特F-450", "福特F-650", "福特GT", "福特Ka", "PUMA", "Tourneo Custom", "Galaxy", "Grand C-MAX", "撼路者(海外)", "金牛座(海外)", "Mad Max", "蒙迪欧(海外)", "S-MAX", "Start", "Super Duty", "Territory", "Tourneo Courier", "Transit", "Vertrek", "翼搏(海外)", "蒙迪欧 插电混动", "锐际PHEV", "领界EV", "C-MAX 插电混动", "Evos", "Mustang 纯电动", "Mustang Mach-E", "Tourneo Custom 插电混动", "探险者 插电混动(进口)", "翼虎 插电混动(进口)"], abc: 'F')
CarBrand.create(id: 72, brand: '菲亚特', models: ["博悦", "菲亚特500", "菲亚特Doblo", "菲跃", "领雅", "朋多", "菲亚特Panda", "菲亚特Strada", "菲亚特Tipo", "菲翔", "致悦", "派朗", "派力奥", "西耶那", "周末风", "Centoventi", "菲亚特500e"], abc: 'F')
CarBrand.create(id: 99, brand: '哈飞', models: ["百利", "哈飞单双排", "骏意", "路宝", "路尊大霸王", "路尊小霸王", "民意", "普面", "锐意", "赛豹Ⅲ", "赛豹V系", "赛马", "松花江", "中意"], abc: 'H')
CarBrand.create(id: 100, brand: '海格', models: ["海格H4E", "海格H7V"], abc: 'H')
CarBrand.create(id: 73, brand: '法拉利', models: ["法拉利488", "法拉利F8", "Roma", "Portofino", "法拉利812", "GTC4Lusso", "法拉利360", "法拉利458", "法拉利575", "法拉利599", "法拉利612", "Enzo", "F12berlinetta", "法拉利456", "California T", "法拉利F430", "法拉利FF", "LaFerrari", "Dino", "法拉利212", "法拉利250 GT", "法拉利275", "法拉利308", "法拉利328", "法拉利348", "法拉利375", "法拉利400", "法拉利410", "法拉利500", "法拉利550", "法拉利F355", "法拉利F40", "法拉利F50", "法拉利GTO", "法拉利J50", "Monza SP1", "Monza SP2", "法拉利P80/C", "Sergio", "法拉利SP38", "法拉利SP3JC", "Stallone", "SF90 Stradale"], abc: 'F')
CarBrand.create(id: 74, brand: '枫叶汽车', models: ["枫叶30X"], abc: 'F')
CarBrand.create(id: 75, brand: 'Fisker', models: ["Ocean"], abc: 'F')
CarBrand.create(id: 76, brand: '福迪', models: ["揽福", "雄师F16", "雄师F22", "飞越SRV", "福迪1021皮卡", "福迪小超人", "雄狮", "福迪四驱皮卡", "探索者Ⅱ", "探索者Ⅲ", "探索者6", "探索者I"], abc: 'F')
CarBrand.create(id: 77, brand: '福汽启腾', models: ["启腾M70 EV", "启腾M70", "启腾V60", "启腾EX80"], abc: 'F')
CarBrand.create(id: 78, brand: '福田', models: ["拓陆者驭途", "拓陆者E3", "萨瓦纳", "拓陆者胜途", "福田征服者", "伽途GT", "伽途ix", "伽途im", "拓陆者E5", "拓陆者E7", "拓陆者S", "萨普", "祥菱M", "图雅诺", "欧马可", "风景G7", "祥菱V", "风景G5", "风景G9", "奥铃CTX", "奥铃TX", "传奇X", "风景冲浪", "风景快捷", "风景快客", "风景", "风景V3", "风景V5", "伽途V3", "伽途V5", "福田海狮", "迷迪", "瑞沃工程用车", "时代康瑞", "时代领航", "时代微卡", "时代骁运", "时代驭菱", "奥铃捷运", "祥菱S", "奥铃EV", "递哥", "风景V5 EV", "图雅诺EV", "风景V3 EV", "拓陆者EV"], abc: 'F')
CarBrand.create(id: 79, brand: 'Faraday Future', models: ["FF 91"], abc: 'F')
CarBrand.create(id: 80, brand: '广汽传祺', models: ["传祺GS4", "传祺GA4", "传祺GS5", "传祺GS8", "传祺GM6", "传祺GA6", "传祺GM8", "传祺GS3", "传祺GA8", "传祺GS7", "传祺GA5", "传祺GA3S 视界", "传祺GS5 Super", "传祺GA3", "传祺GS4 PHEV"], abc: 'G')
CarBrand.create(id: 81, brand: '广汽新能源', models: ["埃安Aion S", "传祺GE3", "埃安Aion LX", "埃安Aion V", "传祺GA3S PHEV", "传祺GA5 PHEV"], abc: 'G')
CarBrand.create(id: 82, brand: '高合HiPhi', models: ["Concept A", "Concept H", "Concept U", "高合HiPhi 1"], abc: 'G')
CarBrand.create(id: 83, brand: '格罗夫', models: ["欧思典"], abc: 'G')
CarBrand.create(id: 84, brand: 'GFG Style', models: ["Bandini Dora", "GFG 2030", "Kangaroo"], abc: 'G')
CarBrand.create(id: 85, brand: '广汽吉奥', models: ["财运300", "奥轩G3", "奥轩G5", "财运100", "财运500", "柴神", "吉奥E美", "吉奥GP150", "吉奥GX6", "吉奥GS50", "奥轩GX5", "凯睿", "帅豹", "帅舰", "星朗", "星旺", "星旺CL", "星旺L", "星旺M1", "星旺M2"], abc: 'G')
CarBrand.create(id: 86, brand: '广汽集团', models: ["广汽丰田iA5", "广汽ix4", "世锐PHEV", "祺智PHEV", "祺智EV"], abc: 'G')
CarBrand.create(id: 87, brand: '广汽日野', models: ["270Y系列", "300J系列", "320D系列"], abc: 'G')
CarBrand.create(id: 88, brand: '观致', models: ["观致5", "观致3", "观致Model Young", "观致7", "观致3 EV"], abc: 'G')
CarBrand.create(id: 89, brand: '国金', models: ["国金GM3"], abc: 'G')
CarBrand.create(id: 90, brand: '国机智骏', models: ["国机智骏GC1", "国机智骏GC2", "国机智骏GX5", "国机智骏GT3"], abc: 'G')
CarBrand.create(id: 91, brand: '国能汽车', models: ["NEVS 93"], abc: 'G')
CarBrand.create(id: 92, brand: 'GMC', models: ["YUKON", "SAVANA", "SIERRA", "CANYON", "HUMMER EV"], abc: 'G')
CarBrand.create(id: 93, brand: '光冈', models: ["嘉路(进口)", "女王(进口)", "大蛇(进口)"], abc: 'G')
CarBrand.create(id: 94, brand: '哈弗', models: ["哈弗H6", "哈弗M6", "哈弗F7", "哈弗H9", "哈弗F5", "哈弗H6 Coupe", "哈弗F7x", "哈弗H7", "哈弗H4", "哈弗H2", "哈弗H5", "哈弗H2s", "哈弗H3", "哈弗H1", "哈弗H8", "哈弗Concept H"], abc: 'H')
CarBrand.create(id: 95, brand: '海马', models: ["海马8S", "海马S5", "海马M6", "海马S5青春版", "福仕达福卡", "福仕达鸿达", "海马王子", "海马爱尚", "海马M3", "福仕达新鸿达", "福仕达荣达", "腾达", "福仕达腾达", "海马6P", "福美来F5", "海马S7", "海福星", "海马3", "丘比特", "骑士", "福美来F7", "马自达323", "欢动", "普力马", "海马M8", "海马7X", "海马E3", "海马爱尚EV"], abc: 'H')
CarBrand.create(id: 96, brand: '汉腾', models: ["汉腾X5", "汉腾X7", "汉腾V7", "汉腾X8", "汉腾X7 PHEV", "汉腾X5 EV", "幸福e+", "汉腾FCV"], abc: 'H')
CarBrand.create(id: 97, brand: '红旗', models: ["红旗H5", "红旗HS5", "红旗HS7", "红旗H7", "红旗H9", "红旗", "红旗旗舰", "红旗盛世", "新明仕", "世纪星", "红旗L5", "红旗S9", "红旗E-HS3", "红旗E115"], abc: 'H')
CarBrand.create(id: 98, brand: '华泰', models: ["圣达菲7", "圣达菲5", "华泰B11", "宝利格", "吉田", "路盛E80", "路盛E70", "经典圣达菲", "特拉卡", "圣达菲", "路盛S1 EV160B", "路盛S1 EV160R", "路盛S1 iEV360", "路盛S5 iEV230", "圣达菲2 XEV360", "圣达菲5 XEV260"], abc: 'H')
CarBrand.create(id: 101, brand: '悍马', models: ["悍马H2", "悍马H3"], abc: 'H')
CarBrand.create(id: 102, brand: '汉龙汽车', models: ["旷世"], abc: 'H')
CarBrand.create(id: 103, brand: '恒天', models: ["恒好EV1", "恒好EV7", "途腾T1", "途腾T2", "途腾T3"], abc: 'H')
CarBrand.create(id: 104, brand: 'Hennessey', models: ["VelociRaptor", "Venom"], abc: 'H')
CarBrand.create(id: 105, brand: 'Hispano Suiza', models: ["Carmen"], abc: 'H')
CarBrand.create(id: 106, brand: '红星汽车', models: ["闪闪X2"], abc: 'H')
CarBrand.create(id: 107, brand: '华凯', models: ["华凯皮卡"], abc: 'H')
CarBrand.create(id: 108, brand: '黄海', models: ["黄海N3", "黄海N7", "黄海N2", "黄海N1", "黄海N1S", "黄海N2S", "黄海N3S", "傲骏", "傲羚", "翱龙", "傲龙CUV", "翱龙CUV", "翱龙SUV", "大柴神", "领航者", "旗胜CUV", "旗胜F1", "旗胜V3", "瑞途", "曙光骄子", "黄海挑战者", "小柴神", "黄海征服者"], abc: 'H')
CarBrand.create(id: 109, brand: '华普', models: ["飚风", "海锋", "海景", "海尚", "海炫", "海迅", "海域", "海悦", "杰士达美鹿", "朗风", "M203"], abc: 'H')
CarBrand.create(id: 110, brand: '华骐', models: ["华骐300E"], abc: 'H')
CarBrand.create(id: 111, brand: '华颂', models: ["华颂7"], abc: 'H')
CarBrand.create(id: 112, brand: '汇众', models: ["德驰", "伊思坦纳"], abc: 'H')
CarBrand.create(id: 113, brand: 'HYCAN合创', models: ["HYCAN 007"], abc: 'H')
CarBrand.create(id: 114, brand: 'Icona', models: ["Vulcano"], abc: 'I')
CarBrand.create(id: 115, brand: 'INKAS', models: ["Sentry Civilian"], abc: 'I')
CarBrand.create(id: 116, brand: '吉利', models: ["博越", "帝豪", "缤越", "帝豪GL", "吉利ICON", "远景", "缤瑞", "远景X6", "星越", "帝豪GS", "博瑞", "远景X3", "嘉际", "远景X1", "远景S1", "金刚", "吉利EC8", "豪情SUV", "豪情", "海景", "美日", "英伦C5", "美人豹", "美日之星", "吉利GC7", "吉利GX2", "吉利GX7", "吉利TX4", "熊猫", "吉利SC3", "吉利SX7", "优利欧", "中国龙", "自由舰", "吉利Preface", "豪越", "帝豪GSe", "缤越PHEV", "星越PHEV", "嘉际PHEV", "博瑞PHEV", "帝豪EV", "帝豪GL PHEV", "帝豪PHEV"], abc: 'J')
CarBrand.create(id: 117, brand: '江淮', models: ["嘉悦A5", "瑞风S4", "嘉悦X7", "瑞风M3", "瑞风M4", "瑞风S3", "帅铃T6", "帅铃T8", "瑞风M5", "星锐", "瑞风S2", "瑞风A60", "瑞风S7", "瑞风S5", "江淮V7", "瑞风M6", "瑞风R3", "宾悦", "和悦", "瑞风M2", "和悦A30", "凌铃", "瑞风", "瑞风S2mini", "瑞铃", "瑞鹰", "帅铃V6", "和悦A13", "悦悦", "嘉悦X4", "嘉悦X8", "江淮iC5", "江淮iEV6E", "江淮iEVS4", "江淮iEV7S", "江淮iEVA50", "江淮iEV7", "江淮iEVA60", "江淮iEV", "江淮iEV6S", "帅铃i3"], abc: 'J')
CarBrand.create(id: 118, brand: '捷豹', models: ["捷豹XEL", "捷豹XFL", "捷豹E-PACE", "捷豹F-TYPE", "捷豹F-PACE", "捷豹XF", "捷豹S-Type", "捷豹XE", "捷豹XK", "捷豹XJ", "捷豹B99", "捷豹C-Type", "捷豹D-Type", "捷豹E-PACE(海外)", "捷豹E-Type", "捷豹SS100", "捷豹X-Type", "捷豹I-PACE", "FUTURE-TYPE", "捷豹C-X75", "捷豹Vision Gran Turismo"], abc: 'J')
CarBrand.create(id: 119, brand: 'Jeep', models: ["牧马人", "大切诺基(进口)", "自由客", "指挥官(进口)", "指南者(进口)", "自由光(进口)", "Gladiator", "指南者", "自由光", "指挥官", "自由侠", "大指挥官", "指挥官PHEV", "指南者PHEV", "大切诺基", "Jeep2500", "切诺基", "牧马人PHEV", "自由侠PHEV"], abc: 'J')
CarBrand.create(id: 120, brand: '捷途', models: ["捷途X70", "捷途X70 Coupe", "捷途X95", "捷途X90", "捷途X70M", "捷途X70S", "捷途X70S EV"], abc: 'J')
CarBrand.create(id: 121, brand: '江铃', models: ["特顺", "域虎9", "域虎7", "域虎5", "顺达窄体", "凯运升级版", "宝典", "凯运强劲版", "域虎3", "顺达宽体", "凯锐800", "宝威", "凯锐", "凯威", "易至EX5", "江铃E100B", "江铃E160", "江铃E200L", "江铃E200N", "易至EV3", "特顺EV", "域虎EV"], abc: 'J')
CarBrand.create(id: 122, brand: '江铃旅居车', models: ["D-MAX越野房车", "全顺旅居房车", "考斯特房车", "全顺T型房车", "途睿欧商务车", "全顺商旅房车", "罗莎房车租赁款", "新全顺商旅房车", "全顺商旅房车经典款", "骐铃T7皮卡房车"], abc: 'J')
CarBrand.create(id: 123, brand: '奇点汽车', models: ["奇点iC3", "奇点iS6"], abc: 'Q')
CarBrand.create(id: 124, brand: '捷达', models: ["捷达VS5", "捷达VS7", "捷达VA3"], abc: 'J')
CarBrand.create(id: 125, brand: '捷尼赛思', models: ["捷恩斯", "捷尼赛思G70", "捷尼赛思G80", "捷尼赛思G90", "捷尼赛思GV80", "Mint"], abc: 'J')
CarBrand.create(id: 126, brand: '几何汽车', models: ["几何A", "几何C"], abc: 'J')
CarBrand.create(id: 127, brand: '金杯', models: ["阁瑞斯", "金杯海狮", "观境", "金杯新快运", "金杯F50", "金杯大海狮", "霸道SUV", "海星", "金杯S50", "金杯小海狮X30", "金杯海狮X30L", "新海狮S", "金杯750", "金杯T52", "金杯T32", "金杯T50", "金杯T20S", "金杯T22S", "金杯T20", "金杯T22", "金杯T30", "海星A7", "海星A9", "金杯S70", "金典", "大力神K5", "西部牛仔", "智尚S35", "智尚S30", "雷龙", "小金牛", "领坤EV"], abc: 'J')
CarBrand.create(id: 128, brand: '金龙', models: ["凯特", "金威", "凯歌", "凯锐浩克", "金龙海狮"], abc: 'J')
CarBrand.create(id: 129, brand: '金旅', models: ["金旅大海狮", "金旅海狮", "金旅新时代海狮", "金旅窄体大海狮", "金旅领特", "金旅客车系列", "金旅考斯特", "金旅海狮EV", "金旅大海狮EV"], abc: 'J')
CarBrand.create(id: 130, brand: '九龙', models: ["九龙A4", "九龙艾菲", "九龙专用车", "九龙商务车", "九龙考斯特", "九龙A5", "九龙A6", "九龙C6", "九龙EM3", "九龙A6E", "九龙EF5", "九龙EM5"], abc: 'J')
CarBrand.create(id: 131, brand: '君马', models: ["赛克5", "美图3", "君马S70", "君马MEET 5"], abc: 'J')
CarBrand.create(id: 132, brand: '钧天汽车', models: ["勇猛者"], abc: 'J')
CarBrand.create(id: 133, brand: '凯迪拉克', models: ["凯迪拉克CT5", "凯迪拉克XT4", "凯迪拉克CT4", "凯迪拉克XT5", "凯迪拉克CT6", "凯迪拉克ATS-L", "凯迪拉克XT6", "凯迪拉克XTS", "SLS赛威", "凯雷德", "凯迪拉克ATS(进口)", "凯迪拉克CTS", "凯迪拉克SRX", "凯迪拉克XLR", "凯迪拉克CT4(海外)", "凯迪拉克CT5(海外)", "凯迪拉克CT6(海外)", "凯迪拉克CT6 插电混动", "Celestiq", "Lyriq"], abc: 'K')
CarBrand.create(id: 134, brand: '凯翼', models: ["凯翼X3", "凯翼E3", "凯翼X5", "炫界", "凯翼C3", "凯翼C3R", "凯翼V3"], abc: 'K')
CarBrand.create(id: 135, brand: '克莱斯勒', models: ["克莱斯勒300C(进口)", "大捷龙(进口)", "城乡", "交叉火力", "PT漫步者", "赛百灵", "Airflow Vision", "大捷龙 插电混动(进口)", "铂锐", "克莱斯勒300C", "大捷龙"], abc: 'K')
CarBrand.create(id: 136, brand: '卡尔曼', models: ["卡尔曼"], abc: 'K')
CarBrand.create(id: 137, brand: '开瑞', models: ["开瑞K60", "开瑞K50", "开瑞优劲", "开瑞优优", "爱卡", "开瑞3", "开瑞杰虎", "开瑞优雅", "开瑞优派", "开瑞优胜", "开瑞优翼", "大象EV", "海豚EV", "开瑞K60EV", "开瑞优劲EV", "开瑞优优EV", "开瑞K50EV", "开瑞EK1"], abc: 'K')
CarBrand.create(id: 138, brand: '开沃汽车', models: ["开沃D07", "开沃D08", "开沃D09", "开沃D10", "开沃D11"], abc: 'K')
CarBrand.create(id: 139, brand: 'Karma', models: ["Karma Revero", "Karma Pininfarina", "Karma SC1 Vision", "Karma SC2"], abc: 'K')
CarBrand.create(id: 140, brand: '卡升汽车', models: ["卡升V-class", "卡升T6", "卡升C10", "卡升威霆"], abc: 'K')
CarBrand.create(id: 141, brand: '卡威', models: ["卡威K150GT", "卡威K1", "路易斯", "卡威W1", "卡威W1 纯电动"], abc: 'K')
CarBrand.create(id: 142, brand: '科尼赛克', models: ["科尼赛克Agera", "科尼赛克CCR", "科尼赛克Gemera", "科尼赛克Jesko"], abc: 'K')
CarBrand.create(id: 143, brand: 'KTM', models: ["X-BOW"], abc: 'K')
CarBrand.create(id: 144, brand: '卡尔森', models: ["卡尔森C25", "卡尔森 GL级", "卡尔森 S级", "卡尔森CCA22"], abc: 'K')
CarBrand.create(id: 145, brand: '雷克萨斯', models: ["雷克萨斯ES", "雷克萨斯NX", "雷克萨斯RX", "雷克萨斯UX", "雷克萨斯LX", "雷克萨斯IS", "雷克萨斯CT", "雷克萨斯LS", "雷克萨斯LM", "雷克萨斯RC", "雷克萨斯LC", "雷克萨斯GS", "雷克萨斯GX", "雷克萨斯SC", "雷克萨斯HS", "雷克萨斯LF-C2", "雷克萨斯LF-CC", "雷克萨斯LF-Ch", "雷克萨斯LF-FC", "雷克萨斯LF-Gh", "雷克萨斯LF-Limitless", "雷克萨斯LF-NX", "雷克萨斯LF-SA", "雷克萨斯LF-Xh", "雷克萨斯UX 纯电动", "雷克萨斯LF-30", "雷克萨斯RC F", "雷克萨斯LFA", "雷克萨斯GS F", "雷克萨斯IS F"], abc: 'L')
CarBrand.create(id: 146, brand: '雷诺', models: ["科雷傲", "科雷缤", "科雷嘉", "ARKANA", "雷诺e诺", "Espace", "卡缤", "风朗", "科雷傲(进口)", "雷诺Duster", "风景", "威赛帝", "塔利斯曼", "纬度", "拉古那", "科雷嘉(海外)", "雷诺4 Luxe", "Alaskan", "Alpine A110", "Alpine Celebration", "Alpine Vision", "Alpine Vision Gran Turismo", "ARKANA(海外)", "Clio", "Coupe Corbusier", "Duster Detour", "Duster Extreme", "Duster Oroch", "Eolab", "Initiale", "Kangoo be bop", "Kwid", "雷诺Lodgy", "雷诺Logan", "Master", "梅甘娜", "R-Space", "Sandero", "Sport RS 01", "Symbol", "Trafic", "Triber", "Twingo", "Twin-Run", "雷诺Wind", "科雷缤 插电混动(海外)", "DeZir", "雷诺e诺(海外)", "EZ-GO", "EZ-PRO", "EZ-ULTIMO", "Frendzy", "Kangoo", "Master 新能源", "Morphoz", "SYMBIOZ", "TREZOR", "Twingo Z.E.", "Twin-Z", "Twizy", "雷诺ZOE", "梅甘娜 插电混动"], abc: 'L')
CarBrand.create(id: 147, brand: '领克', models: ["领克03", "领克05", "领克01", "领克02", "领克06", "领克03 PHEV", "领克02 PHEV", "领克01 PHEV", "领克05 PHEV", "领克06 PHEV"], abc: 'L')
CarBrand.create(id: 148, brand: '林肯', models: ["领航员", "林肯MKZ", "林肯MKC", "航海家(进口)", "林肯大陆", "飞行家(进口)", "林肯MKT", "林肯MKX", "林肯MKS", "冒险家(海外)", "冒险家", "飞行家", "航海家", "飞行家 插电混动", "冒险家 插电混动(海外)", "冒险家 插电混动"], abc: 'L')
CarBrand.create(id: 149, brand: '陆风', models: ["陆风X8", "陆风荣曜", "陆风X5", "陆风逍遥", "陆风X2", "风华", "风尚", "陆风X6", "陆风X7", "陆风X9", "新饰界"], abc: 'L')
CarBrand.create(id: 150, brand: '路虎', models: ["揽胜", "揽胜星脉", "揽胜运动版", "发现", "卫士", "发现神行(进口)", "揽胜极光(进口)", "神行者", "发现运动版(进口)", "揽胜极光", "发现运动版", "发现神行", "揽胜运动版 插电混动", "揽胜 插电混动", "发现运动版 插电混动(进口)", "揽胜极光 插电混动(进口)"], abc: 'L')
CarBrand.create(id: 151, brand: '力帆', models: ["力帆650EV", "力帆820EV", "力帆620EV", "力帆330EV", "迈威EV", "丰顺", "乐途", "力帆320", "力帆330", "力帆530", "力帆620", "力帆630", "力帆720", "力帆820", "力帆X60", "力帆X80", "力帆520", "迈威", "力帆X50", "兴顺", "轩朗", "力帆650"], abc: 'L')
CarBrand.create(id: 152, brand: '铃木', models: ["维特拉", "启悦", "骁途", "羚羊", "锋驭", "天语 尚悦", "天语 SX4", "奥拓", "雨燕", "北斗星", "北斗星X5", "派喜", "浪迪", "利亚纳A6", "利亚纳", "超级维特拉", "凯泽西", "英格尼斯", "速翼特", "吉姆尼", "奥拓(海外)", "HANARE", "HUSTLER", "Spacia", "VITARA(海外)", "Wako SPO"], abc: 'L')
CarBrand.create(id: 153, brand: '劳斯莱斯', models: ["幻影", "库里南", "魅影", "古思特", "曜影", "银魅", "银刺"], abc: 'L')
CarBrand.create(id: 154, brand: '拉达', models: ["泥瓦"], abc: 'L')
CarBrand.create(id: 155, brand: '兰博基尼', models: ["Aventador", "Urus", "Huracán", "Murcielago", "Gallardo", "Centenario", "Countach", "Diablo", "Egoista", "Estoque", "兰博基尼400 GT", "兰博基尼5-95", "兰博基尼LM002", "Sián", "Reventon", "Sesto Elemento", "V12 Vision Gran Turismo", "Veneno", "Asterion", "Terzo Millennio"], abc: 'L')
CarBrand.create(id: 156, brand: '蓝旗亚', models: ["Ypsilon"], abc: 'L')
CarBrand.create(id: 157, brand: '雷诺三星', models: ["雷诺三星QM6", "雷诺三星SM6", "雷诺三星XM3"], abc: 'L')
CarBrand.create(id: 158, brand: 'LEVC', models: ["LEVC TX"], abc: 'L')
CarBrand.create(id: 159, brand: '莲花', models: ["竞悦", "莲花L5", "莲花L3"], abc: 'L')
CarBrand.create(id: 160, brand: '猎豹', models: ["猎豹Mattu", "猎豹CS10", "猎豹Q6", "猎豹CS9", "猎豹CT7", "长丰DUV", "猎豹CS7", "飞铃皮卡", "飞铃SUV", "飞腾", "飞腾C5", "飞扬皮卡", "飞扬SUV", "福铃皮卡", "猎豹黑金刚", "金麒麟", "猎豹CS6", "猎豹CT5皮卡", "猎豹6481", "骐菱", "猎豹Coupe", "猎豹CS9 EV", "猎豹C5 EV", "缤歌"], abc: 'L')
CarBrand.create(id: 161, brand: '凌宝汽车', models: ["凌宝BOX"], abc: 'L')
CarBrand.create(id: 162, brand: '零跑汽车', models: ["零跑S01", "零跑T03", "零跑C-more"], abc: 'L')
CarBrand.create(id: 163, brand: '领途汽车', models: ["领途E行", "领途K-ONE", "领途S3"], abc: 'L')
CarBrand.create(id: 164, brand: '理念', models: ["广汽本田VE-1", "理念S1"], abc: 'L')
CarBrand.create(id: 165, brand: '理想汽车', models: ["理想ONE"], abc: 'L')
CarBrand.create(id: 166, brand: 'Lucid', models: ["Lucid Air"], abc: 'L')
CarBrand.create(id: 167, brand: '罗夫哈特', models: ["罗夫哈特GR500", "罗夫哈特MR500"], abc: 'L')
CarBrand.create(id: 168, brand: '罗伦士', models: ["Lorinser MAYBACH S级", "Lorinser GS", "Lorinser VS", "Sprinter LS500", "Lorinser LS", "Lorinser MS"], abc: 'L')
CarBrand.create(id: 169, brand: '路特斯', models: ["路特斯Evija", "路特斯Evora", "路特斯Exige", "Esprit", "路特斯Elise"], abc: 'L')
CarBrand.create(id: 170, brand: '雷丁', models: ["雷丁i3", "雷丁i5", "雷丁i9"], abc: 'L')
CarBrand.create(id: 171, brand: '马自达', models: ["马自达3 昂克赛拉", "马自达CX-5", "马自达CX-8", "马自达CX-30", "马自达3 星骋", "马自达2", "马自达3", "马自达CX-4", "阿特兹", "马自达6", "马自达8", "马自达CX-7", "睿翼", "马自达CX-3", "马自达MX-5", "马自达CX-7(进口)", "马自达6(进口)", "马自达RX-8", "马自达5", "马自达3(进口)", "马自达2(海外)", "马自达CX-30(海外)", "马自达CX-5(进口)", "马自达CX-9", "VISION COUPE", "马自达MX-30"], abc: 'M')
CarBrand.create(id: 172, brand: '名爵', models: ["名爵6", "名爵ZS", "名爵HS", "名爵3", "名爵GS 锐腾", "名爵5", "名爵GT 锐行", "名爵3SW", "名爵7", "名爵TF", "Hector", "名爵6 插电混动", "名爵eHS", "名爵EZS", "Cyberster"], abc: 'M')
CarBrand.create(id: 173, brand: 'MINI', models: ["MINI", "MINI CLUBMAN", "MINI COUNTRYMAN", "MINI CABRIO", "MINI COUPE", "MINI PACEMAN", "MINI ROADSTER", "MINI JCW", "MINI JCW COUNTRYMAN", "MINI JCW CLUBMAN", "MINI JCW COUPE", "JCW PACEMAN", "MINI COUNTRYMAN 插电混动", "MINI Electric"], abc: 'M')
CarBrand.create(id: 174, brand: 'Mahindra', models: ["KUV 100", "Roxor"], abc: 'M')
CarBrand.create(id: 175, brand: '迈巴赫', models: ["迈巴赫57S", "迈巴赫62S", "迈巴赫57", "迈巴赫62"], abc: 'M')
CarBrand.create(id: 176, brand: '迈凯伦', models: ["迈凯伦720S", "迈凯伦GT", "迈凯伦540C", "迈凯伦600LT", "迈凯伦570S", "迈凯伦570GT", "迈凯伦625C", "迈凯伦650S", "迈凯伦675LT", "迈凯伦12C", "迈凯伦P1", "迈凯伦620R", "迈凯伦765LT", "迈凯伦Elva", "迈凯伦F1", "迈凯伦塞纳", "迈凯伦Speedtail", "迈凯伦X-1"], abc: 'M')
CarBrand.create(id: 177, brand: '迈莎锐', models: ["迈莎锐M580", "迈莎锐库里南"], abc: 'M')
CarBrand.create(id: 178, brand: '玛莎拉蒂', models: ["Ghibli", "Levante", "Quattroporte", "GranCabrio", "GranSport", "Coupe", "GranTurismo", "玛莎拉蒂Spyder", "Alfieri", "玛莎拉蒂MC12", "玛莎拉蒂MC20", "Mostro"], abc: 'M')
CarBrand.create(id: 179, brand: 'Micro', models: ["Microlino"], abc: 'M')
CarBrand.create(id: 180, brand: '摩根', models: ["摩根3-Wheeler", "摩根4-4", "摩根Aero", "摩根Aero 8", "摩根Plus 4", "摩根plus 8", "摩根Roadster"], abc: 'M')
CarBrand.create(id: 181, brand: '哪吒汽车', models: ["哪吒N01", "哪吒U"], abc: 'N')
CarBrand.create(id: 182, brand: '纳智捷', models: ["U5 SUV", "纳智捷URX", "大7 MPV", "优6 SUV", "MASTER CEO", "大7 SUV", "纳5", "锐3", "纳智捷U5 SUV EV"], abc: 'N')
CarBrand.create(id: 183, brand: '讴歌', models: ["讴歌CDX", "讴歌RDX", "讴歌TLX-L", "讴歌MDX", "讴歌NSX", "讴歌ILX", "讴歌RDX(进口)", "讴歌RL", "讴歌TL", "讴歌ZDX", "讴歌RLX", "讴歌TLX", "讴歌TSX", "讴歌Type S", "PRECISION"], abc: 'O')
CarBrand.create(id: 184, brand: '欧拉', models: ["欧拉R1", "欧拉iQ", "欧拉R2"], abc: 'O')
CarBrand.create(id: 185, brand: '欧宝', models: ["欧宝GT", "英速亚", "麦瑞纳", "安德拉", "威达", "雅特", "欧宝Ampera", "欧宝Corsa", "赛飞利", "欧宝Grandland X PHEV", "欧宝Corsa-e"], abc: 'O')
CarBrand.create(id: 186, brand: '欧朗', models: ["欧朗"], abc: 'O')
CarBrand.create(id: 187, brand: '帕加尼', models: ["Huayra", "Zonda"], abc: 'P')
CarBrand.create(id: 188, brand: '佩奇奥', models: ["Cevennes", "Coastline", "Echo", "Hemera"], abc: 'P')
CarBrand.create(id: 189, brand: 'Polestar极星', models: ["Polestar 2", "Polestar 1", "Precept"], abc: 'P')
CarBrand.create(id: 190, brand: 'Puritalia', models: ["Berlinetta"], abc: 'P')
CarBrand.create(id: 191, brand: '奇瑞', models: ["瑞虎7", "瑞虎8", "艾瑞泽5", "瑞虎5x", "瑞虎3x", "艾瑞泽GX", "瑞虎3", "奇瑞A3", "艾瑞泽3", "艾瑞泽M7", "东方之子", "奇瑞E3", "风云", "风云2", "奇瑞A1", "奇瑞A5", "艾瑞泽7", "奇瑞QQ", "奇瑞QQme", "旗云", "旗云1", "旗云2", "旗云3", "旗云5", "奇瑞E5", "奇瑞QQ3", "奇瑞QQ6", "瑞虎", "瑞虎5", "奇瑞X1", "奇瑞eQ1", "瑞虎3xe", "瑞虎e", "艾瑞泽5e", "艾瑞泽e", "艾瑞泽7e", "奇瑞eQ", "奇瑞QQ3EV", "奇瑞eQ5"], abc: 'Q')
CarBrand.create(id: 192, brand: '启辰', models: ["启辰星", "启辰D60", "启辰T90", "启辰T70", "启辰T60", "启辰M50V", "启辰R50", "启辰D50", "启辰R30", "启辰T70X", "启辰R50X", "启辰T60 EV", "启辰e30", "启辰D60 EV", "晨风"], abc: 'Q')
CarBrand.create(id: 193, brand: '起亚', models: ["起亚K3", "智跑", "KX3傲跑", "焕驰", "起亚KX5", "奕跑", "起亚K2", "起亚KX7", "福瑞迪", "凯绅", "KX CROSS", "K5凯酷", "嘉华", "普莱特", "千里马", "起亚K3S", "锐欧", "赛拉图", "狮跑", "秀尔", "远舰", "起亚K5 PHEV", "起亚KX3 EV", "起亚K3 PHEV", "起亚K3 EV", "霸锐", "凯尊", "极睿", "欧菲莱斯", "普莱特(进口)", "嘉华(进口)", "起亚K9", "斯汀格", "Sportage", "速迈", "索兰托", "起亚VQ", "佳乐", "起亚K5(进口)", "Picanto", "起亚Ceed", "Habaniro", "Seltos", "Sonet", "Soul", "Telluride", "起亚XCeed", "Soul 纯电动", "Futuron"], abc: 'Q')
CarBrand.create(id: 194, brand: '前途', models: ["前途K50", "前途K20", "前途K25"], abc: 'Q')
CarBrand.create(id: 195, brand: '乔治·巴顿', models: ["战车", "战剑"], abc: 'Q')
CarBrand.create(id: 196, brand: '骐铃汽车', models: ["骐铃T5", "骐铃T100", "骐铃T7", "骐铃T3", "骐铃T15"], abc: 'Q')
CarBrand.create(id: 197, brand: '庆铃汽车', models: ["庆铃轻型商用车", "庆铃T17", "达咖", "庆铃中型商用车"], abc: 'Q')
CarBrand.create(id: 198, brand: '清源汽车', models: ["清源小尊", "清源尊者"], abc: 'Q')
CarBrand.create(id: 199, brand: '全球鹰', models: ["全球鹰K27", "全球鹰K12", "全球鹰K17", "全球鹰K10D", "全球鹰K11D", "全球鹰EX3"], abc: 'Q')
CarBrand.create(id: 200, brand: '日产', models: ["轩逸", "天籁", "奇骏", "逍客", "骐达", "楼兰", "蓝鸟", "劲客", "骏逸", "骊威", "玛驰", "西玛", "阳光", "颐达", "途达", "日产NV200", "纳瓦拉", "日产D22皮卡", "凯普斯达", "帕拉丁", "帕拉骐", "日产D22厢式车", "日产ZN厢式车", "轩逸·纯电", "蓝鸟(进口)", "日产350Z", "日产370Z", "碧莲", "风度", "风雅", "日产GT-R", "贵士", "日产Pathfinder", "奇骏(进口)", "途乐", "劲客(海外)", "聆风", "玛驰(海外)", "纳瓦拉(海外)", "Note", "日产DAYZ", "日产Frontier", "日产JUKE", "日产Sentra", "日产Serena", "日产Skyline", "日产Titan", "Rogue", "日产Ariya", "日产IMk"], abc: 'R')
CarBrand.create(id: 201, brand: 'Rimac', models: ["Rimac-Concept One", "Rimac-Concept S", "Rimac-Concept Two"], abc: 'R')
CarBrand.create(id: 202, brand: 'RIVIAN', models: ["RIVIAN R1S", "RIVIAN R1T"], abc: 'R')
CarBrand.create(id: 203, brand: '荣威', models: ["荣威RX5", "荣威i5", "荣威RX5 MAX", "荣威i6", "荣威RX8", "荣威RX3", "荣威360", "荣威550", "荣威750", "荣威350", "荣威950", "荣威W5", "荣威i6 MAX", "荣威iM8", "荣威Vision-iM", "荣威ei6 插电混动", "荣威Ei5", "荣威Marvel X", "荣威ERX5 纯电动", "荣威eRX5 插电混动", "荣威RX5 eMAX 插电混动", "科莱威CLEVER", "荣威e950", "荣威e550", "荣威e50", "极光号", "荣威ER6", "荣威ei6 MAX 插电混动", "荣威MARVEL-R"], abc: 'R')
CarBrand.create(id: 204, brand: '如虎', models: ["如虎CTR 3", "如虎XL"], abc: 'R')
CarBrand.create(id: 205, brand: '瑞驰新能源', models: ["瑞驰新能源EC31", "瑞驰新能源EC35", "瑞驰新能源EK05", "瑞驰新能源S513"], abc: 'R')
CarBrand.create(id: 206, brand: '瑞麒', models: ["瑞麒G3", "瑞麒G5", "瑞麒G6", "瑞麒M1", "瑞麒M5"], abc: 'R')
CarBrand.create(id: 260, brand: '依维柯', models: ["依维柯得意", "依维柯欧胜", "依维柯Ouba", "依维柯褒迪", "都灵", "康果", "欧霸", "威尼斯之旅", "Daily", "依维柯褒迪 纯电动"], abc: 'Y')
CarBrand.create(id: 207, brand: '斯柯达', models: ["柯米克", "明锐", "柯迪亚克", "速派", "柯珞克", "昕锐", "柯迪亚克GT", "昕动", "晶锐", "昊锐", "Yeti", "VISION GT", "晶锐(进口)", "欧雅", "昊锐(进口)", "速尊", "Yeti(进口)", "明锐(进口)", "KAMIQ", "SCALA", "VISION IN", "速派(海外)", "昕锐(海外)", "ENYAQ iV", "明锐 插电混动(进口)", "Citigo-e iV", "SCALA G-TEC", "VISION iV"], abc: 'S')
CarBrand.create(id: 208, brand: '斯巴鲁', models: ["森林人", "傲虎", "力狮", "斯巴鲁BRZ", "斯巴鲁XV", "驰鹏", "翼豹", "斯巴鲁WRX", "Ascent", "LEVORG", "VIZIV Adrenaline", "斯巴鲁XV 插电混动"], abc: 'S')
CarBrand.create(id: 209, brand: 'smart', models: ["smart fortwo", "smart forfour", "smart forfour EQ", "smart fortwo EQ"], abc: 'S')
CarBrand.create(id: 210, brand: 'SWM斯威汽车', models: ["SWM斯威X7", "SWM斯威G01", "SWM斯威G05", "SWM斯威X3", "SWM斯威X2", "SWM斯威G01 EV"], abc: 'S')
CarBrand.create(id: 211, brand: '思皓', models: ["思皓E20X"], abc: 'S')
CarBrand.create(id: 212, brand: '萨博', models: ["萨博9-3", "萨博9-5"], abc: 'S')
CarBrand.create(id: 213, brand: '赛麟', models: ["迈迈", "赛麟S1", "赛麟科迈罗", "赛麟领道430S", "赛麟领道300S", "赛麟S7", "赛麟野马", "赛麟迈克", "赛麟S1(进口)"], abc: 'S')
CarBrand.create(id: 214, brand: '三菱', models: ["欧蓝德", "奕歌", "劲炫", "帕杰罗", "帕杰罗·劲畅", "帕杰罗", "帕杰罗·劲畅(进口)", "欧蓝德(进口)", "劲炫(进口)", "格蓝迪", "蓝瑟(进口)", "伊柯丽斯(进口)", "三菱L200", "三菱Mirage", "三菱SUPER HEIGHT K-WAGON", "三菱Xpander", "戈蓝", "君阁", "蓝瑟", "风迪思", "翼神", "菱绅", "经典欧蓝德", "帕杰罗速跑", "三菱Mi-Tech"], abc: 'S')
CarBrand.create(id: 215, brand: 'SERES赛力斯', models: ["金康SERES SF5"], abc: 'S')
CarBrand.create(id: 216, brand: '上汽MAXUS', models: ["上汽MAXUS G50", "上汽MAXUS D60", "上汽MAXUS G10", "上汽MAXUS T70", "上汽MAXUS D90", "上汽MAXUS D90 Pro", "上汽MAXUS G20", "上汽MAXUS V80", "上汽MAXUS T60", "上汽MAXUS V90", "上汽MAXUS RV80", "上汽MAXUS RG10", "上汽MAXUS RV90", "EUNIQ 6 插电混动", "EUNIQ 5 纯电动", "EUNIQ 6 纯电动", "EUNIQ 5 插电混动", "上汽MAXUS EG10", "上汽MAXUS EV30", "上汽MAXUS FCV80", "上汽MAXUS EV80"], abc: 'S')
CarBrand.create(id: 217, brand: '世爵', models: ["世爵C8"], abc: 'S')
CarBrand.create(id: 218, brand: '双环', models: ["来宝S-RV", "来旺", "双环SCEO", "小贵族"], abc: 'S')
CarBrand.create(id: 219, brand: '双龙', models: ["雷斯特G4", "爱腾", "柯兰多", "雷斯特W", "雷斯特II", "路帝", "享御", "主席", "途凌", "蒂维拉"], abc: 'S')
CarBrand.create(id: 220, brand: 'SRM鑫源', models: ["好运1号", "好运2号", "鑫源X30L EV", "小海狮EV", "鑫源T20 EV", "鑫源T50 EV", "鑫源T30S", "鑫源T20S", "鑫源T22S", "鑫源T32S", "鑫源X30L"], abc: 'S')
CarBrand.create(id: 221, brand: 'SSC', models: ["Tuatara"], abc: 'S')
CarBrand.create(id: 222, brand: '索尼', models: ["索尼VISION-S"], abc: 'S')
CarBrand.create(id: 223, brand: '思铭', models: ["本田X-NV", "思铭"], abc: 'S')
CarBrand.create(id: 224, brand: '特斯拉', models: ["Model 3", "Model Y", "Model X", "Model S", "Model Y(进口)", "Model 3(进口)", "Roadster", "Cybertruck"], abc: 'T')
CarBrand.create(id: 225, brand: '腾势', models: ["腾势X 插电混动", "腾势X 纯电动", "腾势"], abc: 'T')
CarBrand.create(id: 226, brand: '唐骏汽车', models: ["赛菱"], abc: 'T')
CarBrand.create(id: 227, brand: '塔塔', models: ["塔塔Sierra EV", "塔塔Nexon EV", "塔塔HBX", "塔塔Nexon"], abc: 'T')
CarBrand.create(id: 228, brand: '天际汽车', models: ["天际ME7", "天际ME-S"], abc: 'T')
CarBrand.create(id: 229, brand: '天美汽车', models: ["天美ET5"], abc: 'T')
CarBrand.create(id: 230, brand: 'Troller', models: ["Troller T4", "Troller TX4"], abc: 'T')
CarBrand.create(id: 231, brand: 'VANTAS', models: ["VANTAS TX"], abc: 'V')
CarBrand.create(id: 232, brand: 'Vega Innovations', models: ["Vega EVX"], abc: 'V')
CarBrand.create(id: 233, brand: 'Vinfast', models: ["Vinfast-LUX A2.0", "Vinfast-LUX SA2.0", "Vinfast-LUX V8"], abc: 'V')
CarBrand.create(id: 234, brand: '五菱汽车', models: ["五菱宏光PLUS", "五菱宏光S", "五菱宏光S3", "五菱宏光S1", "五菱之光", "五菱730", "五菱荣光小卡", "五菱荣光", "五菱宏光V", "五菱荣光新卡", "五菱荣光V", "五菱之光小卡", "五菱之光V", "五菱荣光S", "五菱鸿途", "五菱PN货车", "五菱小旋风", "五菱兴旺", "五菱扬光", "征程", "五菱荣光EV", "宏光MINI EV", "五菱宏光S EV", "五菱50EV"], abc: 'W')
CarBrand.create(id: 259, brand: '一汽', models: ["森雅R7", "森雅R8", "森雅R9", "解放T80", "解放T90", "佳宝V77", "佳宝V80", "佳宝T50", "佳宝T51", "佳宝T57", "佳宝V52", "佳宝V55", "佳宝V70 Ⅱ", "佳宝V70", "森雅M80", "森雅S80", "一汽V75", "一汽奥星", "骏派A50", "骏派D60", "骏派D80", "骏派CX65", "骏派A70", "夏利N7", "威乐", "威志", "威志V5", "威姿", "威志V2", "夏利", "夏利N5", "佳宝V80 EV", "森雅R7 EV", "骏派A70E", "宾果", "坤程", "解放轻型商务车", "一汽佳星幸福使者", "蓝舰T340"], abc: 'Y')
CarBrand.create(id: 235, brand: '沃尔沃', models: ["沃尔沃S60", "沃尔沃XC60", "沃尔沃XC40", "沃尔沃S90", "XC Classic", "沃尔沃XC90", "沃尔沃V60", "沃尔沃V90", "沃尔沃S40(进口)", "沃尔沃S70", "沃尔沃V70", "沃尔沃C70", "沃尔沃S80", "沃尔沃C30", "沃尔沃S90(进口)", "沃尔沃V40", "沃尔沃XC40(进口)", "沃尔沃XC60(进口)", "沃尔沃XC70", "沃尔沃S60(进口)", "沃尔沃XC90 插电混动", "沃尔沃V60 插电混动", "沃尔沃XC40 纯电动", "沃尔沃S90 插电混动", "沃尔沃XC60 插电混动", "沃尔沃S60 插电混动", "沃尔沃S40", "沃尔沃S80L"], abc: 'W')
CarBrand.create(id: 236, brand: 'WEY', models: ["WEY VV6", "WEY VV5", "WEY VV7", "WEY VV7 GT", "WEY VV7 GT PHEV", "WEY P8", "WEY VV7 PHEV", "WEY P8 GT", "WEY-S", "WEY-X"], abc: 'W')
CarBrand.create(id: 237, brand: '蔚来', models: ["蔚来ES6", "蔚来ES8", "蔚来EP9", "蔚来EC6", "蔚来ET7"], abc: 'W')
CarBrand.create(id: 238, brand: '五十铃', models: ["牧游侠", "五十铃D-MAX", "铃拓", "经典瑞迈", "瑞迈S", "翼放ES", "瑞迈EV"], abc: 'W')
CarBrand.create(id: 239, brand: '瓦滋', models: ["Hunter", "Patriot", "SGR Expedition"], abc: 'W')
CarBrand.create(id: 240, brand: '潍柴欧睿', models: ["欧睿"], abc: 'W')
CarBrand.create(id: 241, brand: '潍柴汽车', models: ["潍柴U70", "潍柴XT7"], abc: 'W')
CarBrand.create(id: 242, brand: '威麟', models: ["威麟H3", "威麟H5", "威麟V5", "威麟X5", "威麟H6"], abc: 'W')
CarBrand.create(id: 243, brand: '威马汽车', models: ["威马EX5", "威马EX6", "威马Maven"], abc: 'W')
CarBrand.create(id: 244, brand: '威兹曼', models: ["威兹曼GT", "威兹曼Roadster"], abc: 'W')
CarBrand.create(id: 245, brand: '沃克斯豪尔', models: ["沃克斯豪尔Astra", "沃克斯豪尔Corsa", "沃克斯豪尔Corsa e"], abc: 'W')
CarBrand.create(id: 246, brand: '雪佛兰', models: ["科鲁泽", "迈锐宝XL", "科沃兹", "创酷", "探界者", "沃兰多", "开拓者", "创界", "爱唯欧", "景程", "科鲁兹", "科帕奇", "乐风", "乐风RV", "迈锐宝", "赛欧", "赛欧3", "乐骋", "科迈罗", "索罗德", "库罗德", "斯帕可", "Traverse", "雪佛兰Express", "雪佛兰Trailblazer", "科帕奇(进口)", "沃蓝达", "科尔维特", "探界者(海外)", "雪佛兰Suburban", "雪佛兰Tahoe", "开拓者(海外)", "畅巡", "雪佛兰Bolt", "雪佛兰E-10 Concept"], abc: 'X')
CarBrand.create(id: 247, brand: '雪铁龙', models: ["天逸 C5 AIRCROSS", "雪铁龙C6", "爱丽舍", "雪铁龙C5", "雪铁龙C3-XR", "雪铁龙C4L", "C4世嘉", "云逸 C4 AIRCROSS", "雪铁龙C3L", "富康", "凯旋", "赛纳", "毕加索", "世嘉", "雪铁龙C2", "C4 PICASSO", "雪铁龙C4 AIRCROSS(进口)", "雪铁龙C4", "雪铁龙C5(进口)", "雪铁龙C6(进口)", "雪铁龙C3", "雪铁龙C4 Cactus", "雪铁龙SPACETOURER", "雪铁龙ami", "雪铁龙C5 AIRCROSS 插电混动"], abc: 'X')
CarBrand.create(id: 248, brand: '现代', models: ["悦动", "领动", "现代ix35", "途胜", "胜达", "LAFESTA 菲斯塔", "瑞纳", "索纳塔", "名图", "现代ix25", "悦纳", "逸行", "ENCINO 昂希诺", "悦纳RV", "现代i30", "朗动", "名驭", "瑞奕", "领翔", "御翔", "雅绅特", "伊兰特", "菲斯塔 纯电动", "伊兰特 纯电动", "领动 插电混动", "索纳塔 插电混动", "昂希诺 纯电动", "创虎", "康恩迪", "劳恩斯-酷派", "格越", "辉翼", "劳恩斯", "美佳", "索纳塔(进口)", "Veloster飞思", "维拉克斯", "酷派", "胜达(进口)", "雅尊", "雅科仕", "现代i10", "现代i20", "现代i30(海外)", "现代iMax", "现代KONA", "现代Palisade", "现代RM19", "现代Venue", "伊兰特(海外)", "Nexo", "现代45", "现代IONIQ", "现代Prophecy", "现代Vision T"], abc: 'X')
CarBrand.create(id: 249, brand: '小鹏汽车', models: ["小鹏汽车P7", "小鹏汽车G3"], abc: 'X')
CarBrand.create(id: 250, brand: '新宝骏', models: ["新宝骏RS-3", "新宝骏RS-5", "新宝骏RM-5", "新宝骏RC-6", "新宝骏RC-5", "新宝骏RM-C", "新宝骏RS-7", "新宝骏E300", "新宝骏RS-5 PHEV"], abc: 'X')
CarBrand.create(id: 251, brand: '星途', models: ["星途LX", "星途TX", "星途TXL", "星途VX", "星途LX EV"], abc: 'X')
CarBrand.create(id: 252, brand: '新特汽车', models: ["启能GEV 1", "新特DEV 1", "新特MEV 100"], abc: 'X')
CarBrand.create(id: 253, brand: '西雅特', models: ["欧悦搏", "伊比飒", "西雅特LEON", "Tarraco", "EL-BORN", "西雅特Mii 纯电动", "Tarraco 插电混动"], abc: 'X')
CarBrand.create(id: 254, brand: '英菲尼迪', models: ["英菲尼迪QX50", "英菲尼迪Q50L", "英菲尼迪QX60", "英菲尼迪Q60", "英菲尼迪QX80", "英菲尼迪Q70L", "英菲尼迪QX30", "英菲尼迪Q50", "英菲尼迪ESQ", "英菲尼迪QX50(进口)", "英菲尼迪EX", "英菲尼迪FX", "英菲尼迪G系", "英菲尼迪JX", "英菲尼迪M系", "英菲尼迪QX", "英菲尼迪QX70", "英菲尼迪Q30", "英菲尼迪QX55"], abc: 'Y')
CarBrand.create(id: 255, brand: '驭胜', models: ["驭胜S350", "驭胜S330"], abc: 'Y')
CarBrand.create(id: 256, brand: '野马汽车', models: ["博骏", "野马T80", "斯派卡", "野马T70", "野马F10", "野马F12", "野马F16", "野马F99", "野马EC60", "斯派卡EV", "野马EC30", "野马EC70", "野马星歌"], abc: 'Y')
CarBrand.create(id: 257, brand: '英致汽车', models: ["英致727", "英致G5", "英致737", "英致G3", "潍柴P80", "英致EX1", "英致737 EV"], abc: 'Y')
CarBrand.create(id: 258, brand: '银隆新能源', models: ["艾菲", "银隆5024 EV", "银隆5043 EV"], abc: 'Y')
CarBrand.create(id: 261, brand: '永源', models: ["永源A380", "风景线", "猎鹰", "五星", "庄威"], abc: 'Y')
CarBrand.create(id: 262, brand: '远程汽车', models: ["远程E200", "远程E200S", "远程E5", "远程E6", "远程RE500"], abc: 'Y')
CarBrand.create(id: 263, brand: '裕路', models: ["裕路EV2"], abc: 'Y')
CarBrand.create(id: 264, brand: '云度', models: ["云度π1", "云度π3", "云度π7"], abc: 'Y')
CarBrand.create(id: 265, brand: '云雀汽车', models: ["全界Q1"], abc: 'Y')
CarBrand.create(id: 266, brand: '宇通', models: ["宇通7系"], abc: 'Y')
CarBrand.create(id: 267, brand: '众泰', models: ["众泰T300", "众泰T700", "众泰T600", "众泰T500", "众泰SR7", "众泰Z700", "众泰T800", "众泰T600 Coupe", "众泰Z360", "众泰Z560", "众泰TS5", "大迈X5", "大迈X7", "江南TT", "众泰Z200HB", "众泰Z200", "众泰M300", "众泰2008", "众泰5008", "众泰SR9", "众泰T200", "众泰V10", "众泰Z100", "众泰Z300", "众泰Z500", "众泰E200", "云100", "芝麻", "众泰T300 EV", "众泰Z500 EV", "众泰ET450 EV", "众泰T100 EV"], abc: 'Z')
CarBrand.create(id: 268, brand: '中华', models: ["中华V7", "中华V3", "中华V6", "中华H530", "中华H220", "骏捷", "骏捷Cross", "骏捷FRV", "骏捷FSV", "中华", "中华H3", "中华H320", "中华H230", "中华H330", "酷宝", "中华豚", "中华V5", "尊驰", "中华V9", "中华H230EV", "中华E5"], abc: 'Z')
CarBrand.create(id: 269, brand: 'Zenvo', models: ["Zenvo"], abc: 'Z')
CarBrand.create(id: 270, brand: '知豆', models: ["知豆D2", "知豆D3", "知豆D1", "知豆"], abc: 'Z')
CarBrand.create(id: 271, brand: '之诺', models: ["之诺60H"], abc: 'Z')
CarBrand.create(id: 272, brand: '中兴', models: ["大领主", "小老虎", "威虎", "长铃皮卡", "驰野", "福星皮卡", "金狮", "田野皮卡", "田野SUV", "万禧龙", "威虎G3", "中兴福星SUV", "中兴海豹", "中兴老虎", "旗舰", "无限", "中兴C3", "中兴GX3"], abc: 'Z')
